//
//  OfficialScraperTestsData.swift
//  RepresentsMeTests
//
//  Created by Michael Tirtowidjojo on 2/22/19.
//  Copyright © 2019 11foot8. All rights reserved.
//

import Foundation
@testable import RepresentsMe

class OfficialScraperTestsData {
    
    // The Array of expected officials for testScrapingData()
    static let expectedOfficials:[Official] = [
        Official(0,
                 "Donald J. Trump",
                 "https://www.whitehouse.gov/sites/whitehouse.gov/files/images/45/PE%20Color.jpg",
                 "Republican Party",
                 [["line1": "The White House",
                   "line2": "1600 Pennsylvania Avenue NW",
                   "city": "Washington",
                   "state": "DC",
                   "zip": "20500"]],
                 ["(202) 456-1111"],
                 ["http://www.whitehouse.gov/"],
                 [["type": "GooglePlus",
                   "id": "+whitehouse"],
                  ["type": "Facebook",
                   "id": "whitehouse" ],
                  ["type": "Twitter",
                   "id": "potus"],
                  ["type": "YouTube",
                   "id": "whitehouse"]],
                 "President of the United States",
                 "United States"),
        Official(1,
                 "Mike Pence",
                 "https://www.whitehouse.gov/sites/whitehouse.gov/files/images/45/VPE%20Color.jpg"
            ,
                 "Republican Party",
                 [["line1": "The White House",
                   "line2": "1600 Pennsylvania Avenue NW",
                   "city": "Washington",
                   "state": "DC",
                   "zip": "20500"]],
                 ["(202) 456-1111"],
                 ["http://www.whitehouse.gov/"],
                 [["type": "GooglePlus",
                   "id": "+whitehouse"],
                  ["type": "Facebook",
                   "id": "whitehouse" ],
                  ["type": "Twitter",
                   "id": "VP"]],
                 "Vice-President of the United States",
                 "United States"),
        Official(2,
                 "John Cornyn",
                 "http://bioguide.congress.gov/bioguide/photo/C/C001056.jpg",
                 "Republican Party",
                 [["line1": "517 Hart Senate Office Building",
                   "city": "Washington",
                   "state": "DC",
                   "zip": "20510"]],
                 ["(202) 224-2934"],
                 ["http://www.cornyn.senate.gov/public/"],
                 [["type": "Facebook",
                   "id": "Sen.JohnCornyn"],
                  ["type": "Twitter",
                   "id": "JohnCornyn" ],
                  ["type": "YouTube",
                   "id": "SenJohnCornyn"]],
                 "United States Senate",
                 "Texas"),
        Official(3,
                 "Ted Cruz",
                 "http://www.cruz.senate.gov/files/images/OfficialPortrait.jpg",
                 "Republican Party",
                 [["line1": "404 Russell Senate Office Building",
                   "city": "Washington",
                   "state": "DC",
                   "zip": "20510"]],
                 ["(202) 224-5922"],
                 ["http://www.cruz.senate.gov/"],
                 [["type": "Facebook",
                   "id": "SenatorTedCruz"],
                  ["type": "Twitter",
                   "id": "SenTedCruz" ],
                  ["type": "YouTube",
                   "id": "TedCruzforSenate"],
                  ["type": "YouTube",
                   "id": "SenTedCruz"]],
                 "United States Senate",
                 "Texas"),
        Official(4,
                 "Roger Williams",
                 "http://bioguide.congress.gov/bioguide/photo/W/W000816.jpg",
                 "Republican Party",
                 [["line1": "1708 Longworth House Office Building",
                   "city": "Washington",
                   "state": "DC",
                   "zip": "20515"]],
                 ["(202) 225-9896"],
                 ["http://williams.house.gov/"],
                 [["type": "Facebook",
                   "id": "RepRogerWilliams"],
                  ["type": "Twitter",
                   "id": "RepRWilliams"],
                  ["type": "YouTube",
                   "id": "UCBtfmMMQarjtLB9U_pWMOhw"],
                  ["type": "YouTube",
                   "id": "RogerWilliamsTX"]],
                 "United States House of Representatives TX-25",
                 "Texas's 25th congressional district"),
        Official(5,
                 "Greg Abbott",
                 "",
                 "Republican Party",
                 [["line1": "P.O. Box 12428",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78711"]],
                 ["(512) 463-2000"],
                 ["http://www.governor.state.tx.us/"],
                 [["type": "Twitter",
                   "id": "GovAbbott"],
                  ["type": "YouTube",
                   "id": "UCqTttg2CGGqDmMYR1S0q5Hw"]],
                 "Governor",
                 "Texas"),
        Official(6,
                 "Dan Patrick",
                 "https://www.ltgov.state.tx.us/wp-content/uploads/2015/02/dan_patrick.jpg",
                 "Republican Party",
                 [["line1": "P.O. Box 12068",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78711"]],
                 ["(512) 463-0001"],
                 ["http://www.ltgov.state.tx.us/"],
                 [["type": "Facebook",
                   "id": "ltgovtx"],
                  ["type": "Twitter",
                   "id": "LtGovTX"]],
                 "Lieutenant Governor",
                 "Texas"),
        Official(7,
                 "Steve Adler",
                 "http://www.austintexas.gov/sites/default/files/images/10-one/Adler_Headshot.jpg",
                 "Nonpartisan",
                 [["line1": "P.O. Box 1088",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78767"]],
                 ["(512) 978-2100"],
                 ["http://www.austintexas.gov/department/mayor"],
                 [["type": "Twitter",
                   "id": "mayoradler"],
                  ["type": "Twitter",
                   "id": "AdlerForAustin"],
                  ["type": "YouTube",
                   "id": "UCvAlpXj81fb-8Zf4xgFcqEQ"]],
                 "Mayor",
                 "Austin city"),
        Official(8,
                 "Sid Miller",
                 "",
                 "Republican Party",
                 [["line1": "P.O. Box 12847",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78711"]],
                 ["(512) 463-1408"],
                 ["http://www.texasagriculture.gov/About/CommissionerMiller.aspx"],
                 [["type": "Facebook",
                   "id": "Texas-Department-of-Agriculture"],
                  ["type": "Twitter",
                   "id": "TexasDeptofAg"]],
                 "Commissioner of Agriculture",
                 "Texas"),
        Official(9,
                 "Christi Craddick",
                 "",
                 "Republican Party",
                 [["line1": "P.O. Drawer 12967",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78711"]],
                 ["(512) 463-7140"],
                 ["https://www.rrc.state.tx.us/about-us/commissioners/craddick/"],
                 [],
                 "Commissioner, Railroad Commission",
                 "Texas"),
        Official(10,
                 "Ryan Sitton",
                 "",
                 "Republican Party",
                 [["line1": "P.O. Drawer 12967",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78711"]],
                 ["(512) 463-7144"],
                 ["https://www.rrc.state.tx.us/about-us/commissioners/sitton/"],
                 [],
                 "Commissioner, Railroad Commission",
                 "Texas"),
        Official(11,
                 "Wayne Christian",
                 "",
                 "Republican Party",
                 [["line1": "P.O. Drawer 12967",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78711"]],
                 ["(512) 463-7133"],
                 ["https://www.rrc.state.tx.us/about-us/commissioners/christian/"],
                 [],
                 "Commissioner, Railroad Commission",
                 "Texas"),
        Official(12,
                 "Glenn Hegar",
                 "",
                 "Republican Party",
                 [["line1": "P.O. Box 13528",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78774"]],
                 ["(512) 463-4444"],
                 ["https://comptroller.texas.gov/"],
                 [["type": "Twitter",
                   "id": "txcomptroller"]],
                 "Comptroller of Public Accounts",
                 "Texas"),
        Official(13,
                 "George P. Bush",
                 "",
                 "Republican Party",
                 [["line1": "P.O. Box 12873",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78711"]],
                 ["(512) 463-5256"],
                 ["http://www.glo.texas.gov/"],
                 [["type": "Twitter",
                   "id": "txglo"]],
                 "Commissioner of General Land Office",
                 "Texas"),
        Official(14,
                 "Ken Paxton",
                 "",
                 "Republican Party",
                 [["line1": "P.O. Box 12548",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78711"]],
                 ["(512) 463-2100"],
                 ["https://www.texasattorneygeneral.gov/"],
                 [["type": "Twitter",
                   "id": "TXAG"]],
                 "Attorney General",
                 "Texas"),
        Official(15,
                 "Bruce Elfant",
                 "",
                 "",
                 [["line1": "5501 Airport Blvd.",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78751"]],
                 ["(512) 854-9473"],
                 [],
                 [["type": "Facebook",
                   "id": "TravisCountyTaxOffice"],
                  ["type": "Twitter",
                   "id": "TravisCountyTax"]],
                 "Tax Assessor-Collector",
                 "Travis County"),
        Official(16,
                 "Sally Hernandez",
                 "",
                 "Democratic Party",
                 [["line1": "P.O. Box 1748",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78767"]],
                 ["(512) 854-9770"],
                 ["https://www.tcsheriff.org/"],
                 [["type": "Facebook",
                   "id": "TravisCOSheriff"],
                  ["type": "Twitter",
                   "id": "TravisCoSheriff"]],
                 "Sheriff",
                 "Travis County"),
        Official(17,
                 "Sarah Eckhardt",
                 "",
                 "",
                 [["line1": "PO Box 1748",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78767"]],
                 ["(512) 854-9555"],
                 ["https://www.traviscountytx.gov/commissioners-court/county-judge"],
                 [["type": "Twitter",
                   "id": "JudgeEckhardt"]],
                 "County Judge",
                 "Travis County"),
        Official(18,
                 "Velva Price",
                 "",
                 "",
                 [["line1": "P.O. Box 679003",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78767"]],
                 ["(512) 854-9457"],
                 ["https://www.traviscountytx.gov/district-clerk"],
                 [],
                 "District Clerk",
                 "Travis County"),
        Official(19,
                 "Carlos H. Barrera",
                 "",
                 "Democratic Party",
                 [["line1": "509 West 11th",
                   "line2": "5th floor",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78701"]],
                 ["(512) 854-7180"],
                 ["https://www.traviscountytx.gov/courts/criminal/county/cc8"],
                 [],
                 "Travis County Court at Law Judge",
                 "Travis County"),
        Official(20,
                 "Kim Williams",
                 "",
                 "Democratic Party",
                 [["line1": "509 West 11th Street",
                   "line2": "6th floor",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78701"]],
                 ["(512) 854-8460"],
                 ["https://www.traviscountytx.gov/courts/criminal/county/cc9"],
                 [],
                 "Travis County Court at Law Judge",
                 "Travis County"),
        Official(21,
                 "David Escamilla",
                 "",
                 "Democratic Party",
                 [["line1": "PO Box 1748",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78767"]],
                 ["(512) 854-9415"],
                 ["https://www.traviscountytx.gov/county-attorney"],
                 [],
                 "Travis County Attorney",
                 "Travis County"),
        Official(22,
                 "Dana DeBeauvoir",
                 "",
                 "",
                 [["line1": "PO Box 149325",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78714"]],
                 ["(512) 854-9188"],
                 [],
                 [["type": "Facebook",
                   "id": "traviscountyclerk"],
                  ["type": "Twitter",
                   "id": "TravisCoClerk"]],
                 "County Clerk",
                 "Travis County"),
        Official(23,
                 "Margaret Moore",
                 "",
                 "Democratic Party",
                 [],
                 [],
                 [],
                 [],
                 "District Attorney",
                 "Travis County"),
        Official(24,
                 "Dolores Ortega-Carter",
                 "",
                 "",
                 [["line1": "700 Lavaca",
                   "line2": "Suite 1.300",
                   "city": "Austin",
                   "state": "TX",
                   "zip": "78701"]],
                 ["(512) 854-9365"],
                 ["https://www.traviscountytx.gov/treasurer"],
                 [],
                 "County Treasurer",
                 "Travis County"),
    ]
    
    // The JSON string for testDivisionMissingName()
    static let invalid_division_json_string =
        """
        {
        "ocd-division/country:us/state:tx": {
           "officeIndices": [
            2,
            4,
            5,
            7,
            8,
            9,
            10,
            11
           ]
          }
        }
        """
    
    // The JSON string for testOfficeMissingName()
    static let invalid_office_json_string =
        """
        {
          "divisionId": "ocd-division/country:us",
          "levels": [
           "country"
          ],
          "roles": [
           "headOfState",
           "headOfGovernment"
          ],
          "officialIndices": [
           0
          ]
        }
        """
    
    // The JSON string for testOfficialMissingaName()
    static let invalid_official_json_string =
        """
        {
           "address": [
            {
             "line1": "The White House",
             "line2": "1600 Pennsylvania Avenue NW",
             "city": "Washington",
             "state": "DC",
             "zip": "20500"
            }
           ],
           "party": "Republican Party",
           "phones": [
            "(202) 456-1111"
           ],
           "urls": [
            "http://www.whitehouse.gov/"
           ],
           "photoUrl": "https://www.whitehouse.gov/sites/whitehouse.gov/files/images/45/PE%20Color.jpg",
           "channels": [
            {
             "type": "GooglePlus",
             "id": "+whitehouse"
            },
            {
             "type": "Facebook",
             "id": "whitehouse"
            },
            {
             "type": "Twitter",
             "id": "potus"
            },
            {
             "type": "YouTube",
             "id": "whitehouse"
            }
           ]
        }
        """
}
